from hosts_automation.update_lists import write_custom_file, write_domain_list
from hosts_automation.domains import read_domain_file

def test_write_domain_list_groups_by_source():
  class Output:
    def __init__(self):
      self.text = ""
      self.parent = self
    def mkdir(self, **kwargs):
      pass
    def write_text(self, text, encoding):
      self.text = text

  output = Output()
  written = write_domain_list(
    output,
    {"custom.example.com", "ads.example.com"},
    [("https://source.example/list.txt", {"ads.example.com", "track.example.com"})],
    set(),
  )
  text = output.text
  assert "# Generated by hosts-automation update-blocklist" in text
  assert "# === Custom entries from custom.txt ===" in text
  assert "custom.example.com" in text
  assert "# === Source: https://source.example/list.txt ===" in text
  assert "track.example.com" in text
  assert written == {"custom.example.com", "ads.example.com", "track.example.com"}

def test_write_custom_file_keeps_clean_domains(tmp_path):
  output = tmp_path / "custom.txt"
  write_custom_file(output, {"custom.example.com", "ads.example.com"})
  assert read_domain_file(output) == {"custom.example.com", "ads.example.com"}
  assert "# Domains already covered by sources.txt are pruned" in output.read_text(encoding="utf-8")
