from __future__ import annotations

import argparse
import re
from pathlib import Path

from hosts_automation.domains import normalize_domain, read_domain_file

TRUSTED_TELEMETRY_KEYWORDS = {
  "ad",
  "ads",
  "advert",
  "analytics",
  "beacon",
  "click",
  "collect",
  "crashlytics",
  "metric",
  "metrics",
  "pixel",
  "stat",
  "stats",
  "telemetry",
  "track",
  "tracker",
  "tracking",
}
DANGEROUS_STRUCTURAL_REASONS = {
  "random-looking-label",
  "deep-subdomain",
}
PROVIDER_SUFFIXES = (
  ".amazonaws.com",
  ".compute.amazonaws.com",
  ".cloudfront.net",
  ".azure.com",
  ".azurewebsites.net",
  ".googleusercontent.com",
  ".scw.cloud",
  ".ptr.pfcloud.network",
  ".in-addr.arpa",
)

CANDIDATE_RE = re.compile(
  r"^(?P<domain>\S+)\s+#\s+score=(?P<score>\d+)\s+count=(?P<count>\d+)\s+reasons=(?P<reasons>.*)$"
)

def parse_candidate_line(line: str) -> tuple[str, int, int, set[str]] | None:
  match = CANDIDATE_RE.match(line.strip())
  if not match:
    return None
  domain = normalize_domain(match.group("domain"))
  if not domain:
    return None
  reasons_raw = match.group("reasons")
  reasons = {reason.split("=", 1)[0] for reason in reasons_raw.split(",") if reason}
  keywords = next((reason for reason in reasons_raw.split(",") if reason.startswith("keywords=")), "")
  if keywords:
    reasons.update(keyword.strip() for keyword in keywords.removeprefix("keywords=").split(",") if keyword.strip())
  return domain, int(match.group("score")), int(match.group("count")), reasons

def is_high_confidence(domain: str, score: int, count: int, reasons: set[str], min_score: int, min_count: int) -> tuple[bool, str]:
  if domain.endswith(PROVIDER_SUFFIXES) and not (reasons & TRUSTED_TELEMETRY_KEYWORDS):
    return False, "provider-infrastructure"
  if score < min_score:
    return False, "score-too-low"
  if count < min_count:
    return False, "count-too-low"
  if reasons & TRUSTED_TELEMETRY_KEYWORDS:
    return True, "telemetry-keyword"
  if "high-volume" in reasons and not (reasons & DANGEROUS_STRUCTURAL_REASONS):
    return True, "high-volume"
  return False, "weak-heuristic-only"

def format_blocklist(domains: set[str]) -> str:
  return "\n".join(sorted(domains)) + "\n"

def approve(args: argparse.Namespace) -> int:
  existing = read_domain_file(args.blocklist)
  allowlist = read_domain_file(args.allowlist)
  approved: set[str] = set()
  rejected: list[tuple[str, str]] = []

  for line in args.candidates.read_text(encoding="utf-8", errors="ignore").splitlines():
    if not line.strip() or line.startswith("#"):
      continue
    parsed = parse_candidate_line(line)
    if not parsed:
      continue
    domain, score, count, reasons = parsed
    if domain in existing or domain in allowlist:
      continue
    ok, reason = is_high_confidence(domain, score, count, reasons, args.min_score, args.min_count)
    if ok:
      approved.add(domain)
    else:
      rejected.append((domain, reason))

  if args.dry_run:
    print(f"Would approve: {len(approved)}")
  else:
    args.blocklist.write_text(format_blocklist(existing | approved), encoding="utf-8")
    print(f"Approved: {len(approved)}")
  print(f"Skipped: {len(rejected)}")
  if approved:
    print("\nApproved domains:")
    for domain in sorted(approved):
      print(domain)
  return 0

def build_parser() -> argparse.ArgumentParser:
  parser = argparse.ArgumentParser(description="Approve high-confidence candidates into block.txt.")
  parser.add_argument("--candidates", type=Path, default=Path("candidates.txt"), help="Candidate file generated by discover-candidates.")
  parser.add_argument("--blocklist", type=Path, default=Path("block.txt"), help="Blocklist to append/update.")
  parser.add_argument("--allowlist", type=Path, default=Path("allowlist.txt"), help="Domains that must never be blocked.")
  parser.add_argument("--min-score", type=int, default=30, help="Minimum candidate score to auto-approve.")
  parser.add_argument("--min-count", type=int, default=5, help="Minimum query count to auto-approve.")
  parser.add_argument("--dry-run", action="store_true", help="Only show what would be approved.")
  return parser

def main(argv: list[str] | None = None) -> int:
  return approve(build_parser().parse_args(argv))

if __name__ == "__main__":
  raise SystemExit(main())
