from __future__ import annotations

import argparse
import datetime as dt
import sys
import urllib.error
import urllib.request
from pathlib import Path

from tqdm import tqdm

from hosts_automation.domains import extract_domains, read_domain_file

DEFAULT_TIMEOUT = 30


def load_sources(path: Path) -> list[str]:
  sources: list[str] = []
  for raw_line in path.read_text(encoding="utf-8").splitlines():
    line = raw_line.strip()
    if not line or line.startswith("#"):
      continue
    sources.append(line)
  return sources


def fetch_url(url: str, timeout: int = DEFAULT_TIMEOUT) -> str:
  request = urllib.request.Request(url, headers={"User-Agent": "hosts-automation/0.1"})
  with urllib.request.urlopen(request, timeout=timeout) as response:  # noqa: S310 - configured user-maintained sources
    charset = response.headers.get_content_charset() or "utf-8"
    return response.read().decode(charset, errors="ignore")


def header(title: str) -> list[str]:
  now = dt.datetime.now(dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
  return [
    "# hosts blocklist",
    "# Plain domain list for pfBlockerNG DNSBL and Pi-hole.",
    "# Generated by hosts-automation update-blocklist",
    f"# Updated: {now}",
    f"# {title}",
    "",
  ]


def custom_header() -> list[str]:
  now = dt.datetime.now(dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
  return [
    "# Custom hosts blocklist entries",
    "# Manual domains and domains approved from local pfSense log review.",
    "# Domains already covered by sources.txt are pruned by update-blocklist.",
    f"# Updated: {now}",
    "",
  ]

def write_custom_file(path: Path, domains: set[str]) -> None:
  path.write_text("\n".join(custom_header() + sorted(domains)) + "\n", encoding="utf-8")

def write_domain_list(path: Path, custom: set[str], source_domains: list[tuple[str, set[str]]], allowlist: set[str]) -> set[str]:
  written: set[str] = set()
  body = header("Generated from custom.txt and sources.txt")

  custom = custom - allowlist
  if custom:
    body.extend(["# === Custom entries from custom.txt ===", f"# Entries: {len(custom)}"])
    body.extend(sorted(custom))
    body.append("")
    written.update(custom)

  for url, domains in source_domains:
    new_for_section = (domains - written) - allowlist
    if not new_for_section:
      continue
    body.extend([f"# === Source: {url} ===", f"# Entries: {len(new_for_section)}"])
    body.extend(sorted(new_for_section))
    body.append("")
    written.update(new_for_section)

  path.parent.mkdir(parents=True, exist_ok=True)
  path.write_text("\n".join(body), encoding="utf-8")
  return written


def update(args: argparse.Namespace) -> int:
  sources = load_sources(args.sources)
  allowlist = read_domain_file(args.allowlist)
  custom = read_domain_file(args.custom)

  failures: list[str] = []
  source_domains: list[tuple[str, set[str]]] = []

  for url in tqdm(sources, desc="Fetching feeds", unit="feed"):
    try:
      text = fetch_url(url, timeout=args.timeout)
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
      failures.append(f"{url} :: {exc}")
      continue
    domains = extract_domains(text) - allowlist
    source_domains.append((url, domains))

  fetched_domains = set().union(*(domains for _, domains in source_domains)) if source_domains else set()
  pruned_custom = (custom - fetched_domains) - allowlist
  removed_from_custom = custom - pruned_custom
  if args.prune_custom:
    write_custom_file(args.custom, pruned_custom)
  written = write_domain_list(args.output, pruned_custom, source_domains, allowlist)

  print(f"Sources configured: {len(sources)}")
  print(f"Sources fetched: {len(source_domains)}")
  print(f"Source failures: {len(failures)}")
  print(f"Custom domains before prune: {len(custom)}")
  print(f"Custom domains after prune: {len(pruned_custom)}")
  print(f"Removed from custom because sourced/allowlisted: {len(removed_from_custom)}")
  print(f"Fetched domains: {len(fetched_domains)}")
  print(f"New sourced domains beyond custom.txt: {len(fetched_domains - custom)}")
  print(f"Output domains: {len(written)}")
  if failures:
    print("\nFailures:", file=sys.stderr)
    for failure in failures:
      print(f"- {failure}", file=sys.stderr)
    return 2 if args.fail_on_source_error else 0
  return 0


def build_parser() -> argparse.ArgumentParser:
  parser = argparse.ArgumentParser(description="Update pfBlockerNG/Pi-hole-compatible domain blocklist from custom entries and configured feeds.")
  parser.add_argument("--sources", type=Path, default=Path("sources.txt"), help="File with one feed URL per line.")
  parser.add_argument("--custom", type=Path, default=Path("custom.txt"), help="Local/manual domains to preserve.")
  parser.add_argument("--allowlist", type=Path, default=Path("allowlist.txt"), help="Domains that must never be written.")
  parser.add_argument("--output", type=Path, default=Path("block.txt"), help="Generated output domain list for pfBlockerNG/Pi-hole.")
  parser.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT, help="Per-source HTTP timeout in seconds.")
  parser.add_argument("--no-prune-custom", dest="prune_custom", action="store_false", help="Do not rewrite custom.txt without domains already covered by sources.")
  parser.set_defaults(prune_custom=True)
  parser.add_argument("--fail-on-source-error", action="store_true", help="Exit non-zero if any source fails.")
  return parser


def main(argv: list[str] | None = None) -> int:
  return update(build_parser().parse_args(argv))


if __name__ == "__main__":
  raise SystemExit(main())
